### ISSUE TITLE
Raspberry pi onboard i2c

### ISSUE THREAD

**Issue by macdroid53** [ncd-io/ncd-red-ads1115#1]
Should this work with the PI onboard i2c port?

When I select I2C and i2c-1 the  I2C Connection combobox is outlined in red and the error triangle never goes away.

**Comment by zaphod-42** [comment]
That error typically implies that the "add" button wasn't clicked after i2c-1 was selected, I'll try to get a test set up today, but we have previously tested on the native I2C port on the rasbpi without issue

**Comment by zaphod-42** [comment]
I just set it up and noticed an issue with the default values on the I2C Connection, go ahead and set the multiplexer drop downs to something, you can leave the "Use Multiplexer" option unchecked and it should be fine, I'll see if I can get this corrected today.

**Comment by zaphod-42** [comment]
I've updated the dependency package to handle the default values appropriately. Closing
