### ISSUE TITLE
Ras Pi 3 B+ I2C error.

### ISSUE THREAD

**Issue by imoldovavan** [ncd-io/ncd-red-ads1115#3]
I get this error on the debug and the sensor is disconnected:
"TypeError: Cannot read property 'sensor' of undefined".
The pi is freshly dist-updated and I installed then node thru Node-red "Manage Pallete"
I have played with the multi plexer settings, On, Off and different values, and a bunch of other stuff.
If I use the I2C scanner the ADS1115 shows up just fine. It even works with the ADS 1X15 node. 
Please help :).
Thank you,
iM

**Comment by zaphod-42** [comment]
Can you post the ncd-red-ads1115 version you have installed and an export of the node?

**Comment by imoldovavan** [comment]
Apparently it has something to do with the operating mode. It seams to be working when I switch from Auto to Power Down Single Shot.

[{"id":"1b757fe7.4994c","type":"ncd-ads1115","z":"70292051.eba3","name":"ttttr","connection":"632561d2.caa9d","addr":"72","interval":"1000","outputs":2,"output_all":true,"output_mult":"0.0003442","channel_1":"4","channel_2":"_none","channel_3":"_none","channel_4":"_none","gain":2,"mode":"1","rate":4,"compMode":0,"compPol":0,"compLat":0,"compQueue":3,"delay":"100","x":530,"y":660,"wires":[["58aae054.b2604"],[]]},{"id":"632561d2.caa9d","type":"ncd-comm","z":"","name":"hh","bus":"i2c-1","commType":"standard","addr":"0","useMux":false,"muxAddr":"112","muxPort":"0"}]

**Comment by imoldovavan** [comment]
Version is 1.2.2

**Comment by zaphod-42** [comment]
Looks like I had a typo that created a scope issue when in auto mode, I've rolled out version 1.2.3 and it should work as expected now, thanks for reporting this!

**Comment by imoldovavan** [comment]
Glad I could help.
Good work. Cheers...

**Comment by imoldovavan** [comment]
I get the same error if I switch to Continuous Conversion.
