### ISSUE TITLE
Says connected but I have no output

### ISSUE THREAD

**Issue by Barabba11** [ncd-io/ncd-red-ads1115#6]
Maybe it nees a "trigger" from the input? Which one should I send it? Anything from any output, I connected debug which work for other devices.

**Comment by zaphod-42** [comment]
What platform are you on? Can you post an export fo the relevant nodes?

**Comment by Barabba11** [comment]
THank you for kindly support me! I'm on raspberry 3, latest version of Raspbian, Red node, and your module
[{"id":"fef64de3.66c588","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"cfc34e3f.3c648","type":"debug","z":"fef64de3.66c588","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":820,"y":400,"wires":[]},{"id":"d12d0c64.a720e8","type":"inject","z":"fef64de3.66c588","name":"","topic":"","payload":"trigger","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":400,"wires":[["fa8a38aa.82a28"]]},{"id":"fa8a38aa.82a28","type":"ncd-ads1115","z":"fef64de3.66c588","name":"","connection":"2ab606d1.4ab30a","addr":"74","interval":"0","outputs":4,"output_all":true,"output_mult":1,"channel_1":"0","channel_2":"_none","channel_3":"6","channel_4":"7","gain":"0","mode":"2","rate":"0","compMode":"1","compPol":"1","compLat":"0","compQueue":"3","delay":"100","x":480,"y":400,"wires":[["cfc34e3f.3c648"],["cfc34e3f.3c648"],["cfc34e3f.3c648"],["cfc34e3f.3c648"]]},{"id":"2ab606d1.4ab30a","type":"ncd-comm","z":"","name":"We","bus":"i2c-1","commType":"standard","addr":"0","useMux":true,"muxAddr":"112","muxPort":"0"}]

**Comment by Barabba11** [comment]
may you kindly tell me if it needs any trigger at input to work? Any message inected?<
To be sincere with you I changed on ncd-ads1115.html the value 72 and 73 with value 74, because my hardware is mapped on this address, (hex 0x4a) and I can't change it.. 
I checked all the scripts and I think it's enough to change it there, it says connected so it comunicate with I2C device

**Comment by zaphod-42** [comment]
You can either send a message with the topic "get_status" in, or set an interval.

**Comment by Barabba11** [comment]
when I do that (topic "get_status") I see for 0,3 seconds a disconnected and then connected again. No output on any of the 5 outputs, never had. What can it be? How can I help you to debug?

**Comment by zaphod-42** [comment]
I'm not really sure, are there any error messages in the shell? I've never had an ADS1115 with 74 as an address option since there is only 1 address pin

**Comment by Barabba11** [comment]
I'm sure ADS works because I tested it with RaspiArduino script, and your module comunicate with it somehow, just the output is silent. No errors from it in the log
When I installed the module, trying to changing the 72 to 74 I uninstalled the package ncd-red-ads1115  but ncd-red-comm was still in use. I tried to reboot, remove manually, cleared all the flow and reboot, mtp reinstall, install from zip, nothing corrected the problem, always in use (??), every time I execute node red it said it was a missing component, even if the folder with files was there. Only the installation from web site-palette followed by reboot solved it, now no more errors. Maybe that corrupted something? Strange.. now all files in the right place.
Anyway how can uninstall ncd-red-comm if I want? I don't see how..
Do you have any ideas how can I debug it?

**Comment by Barabba11** [comment]
10 Jan 20:15:15 - [info] Starting flows
10 Jan 20:15:15 - [info] Started flows
      pi : TTY=unknown ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/python -u /home/pi/.node-red/node_modules/node-red-contrib-lcd20x4-i2c/LCD20x4-I2C/lcd20x4_i2c.py writelcd 20x4 3
pam_unix(sudo:session): session opened for user root by (uid=0)
10 Jan 20:36:56 - [info] Stopping flows
pam_unix(sudo:session): session closed for user root
10 Jan 20:36:57 - [info] Stopped flows
10 Jan 20:36:57 - [info] Starting flows
10 Jan 20:36:57 - [info] Started flows
10 Jan 20:38:49 - [info] Stopping flows
10 Jan 20:38:49 - [info] Stopped flows
10 Jan 20:38:49 - [info] Starting flows
10 Jan 20:38:49 - [info] Started flows
10 Jan 20:39:29 - [info] Stopping flows
10 Jan 20:39:29 - [info] Stopped flows
10 Jan 20:39:29 - [info] Starting flows
10 Jan 20:39:29 - [info] Started flows
no errors

why it says "disconnect" and after it connects again when I inject a get_status topic?

**Comment by zaphod-42** [comment]
I've never had that issue with ncd-red-comm being "sticky", I just ran a test and when I uninstalled ncd-red-ads1115 it also removed ncd-red-comm. Try setting an interval on the ads1115 node instead of injecting and see if that works

**Comment by Barabba11** [comment]
Dear friend, thank you for assisting me, it works, but is it not really clear why it didn't work before:
THe problem was interval, can't be 1.. please write next to it "ms" and advice people they may have no output if the conversion is such fast. 
Anyway I still have some dubts from the outputs values I'm having, I let you know

**Comment by zaphod-42** [comment]
Glad it's working, I'll add the ms in the next revision (it is in the help text for the node, but I understand it could be easier to find). I'm going to close this ticket since you are getting output now, feel free to open another if you have any more issues.

**Comment by Barabba11** [comment]
Hi there! I need again your help!
So as soon I connected a trimmer to every channel to test it I noticed that the module output channel 1 is connected to physical ADC3 input, and it displays about the same result (some time equal, some dime it differs from some units) to module output 4. Channels 2 and 3 output the same values, of channel ADC1.
This may be generated from wrong settings of MUX inside ADS1115, in your module I can configure address of mux and its port, I don't know what these datas are useful to, I've read in ADS1115 datasheet, the mux can be configured from config register as well as other functions existing in your module such comparator and so on, ADS1115 has not other I2C address. IN MUX is possible to choose I2C address  as 112 to 119, and port, is is an eventually external MUX too? In this case I've to ignore it, but the settings "single ended" where I suppose to configure the internal mux I have random effects, for example:
I enable all inputs "single end", I have low voltage on ADC3, and I see the output ar ch4. If I disable the channel 2 I don't see more low voltage pin, ch1,3,4 have high disconnected line.
Can you please help me? Thank you!

**Comment by Barabba11** [comment]
In normal situation (all lines "single end") I have ADC1 who affects ch2 and ch3 with same value, ADC2 ignored, ADC3 who affects ch1 and ch4 with slight differences, ADC4 ignored

Seeing datasheet is not clear if you can set these register only first time and forget about them.. it looks before acquire a value they need to be set according the pin to read:
000 : AINP= AIN0 and AINN= AIN1(default)
001 : AINP= AIN0and AINN= AIN3
010 : AINP= AIN1and AINN= AIN3
011 : AINP= AIN2and AINN= AIN3
100 : AINP= AIN0and AINN= GND
101 : AINP= AIN1and AINN= GND
110 : AINP= AIN2and AINN= GND
111 : AINP= AIN3 and AINN= GND

for read pure ADC0 (that I named before ADC1) we need to set mux before to bit 100, for ADC1 101, etc.
